import { FormEvent, useCallback, useEffect, useState } from 'react';
import { BusFront, CalendarDays, CheckCircle2, Clock3, Edit3, KeyRound, LogOut, Mail, MapPin, Menu, ShieldCheck, UserRound, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import Brand from '../components/Brand';
import PasswordField from '../components/PasswordField';
import { useAuth } from '../contexts/AuthContext';
import supabase from '../lib/supabase';

type Profile={id:number;user_id:string;full_name:string;email:string;role:string;status:string;created_at:string};
export default function Dashboard(){const{user,session,signOut}=useAuth();const[profile,setProfile]=useState<Profile|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[editing,setEditing]=useState(false);const[name,setName]=useState('');const[passwordOpen,setPasswordOpen]=useState(false);const[newPassword,setNewPassword]=useState('');const[toast,setToast]=useState('');const[navOpen,setNavOpen]=useState(false);
const api=useCallback(async(method='GET',body?:object)=>{const res=await fetch('/api/profiles',{method,headers:{'Content-Type':'application/json','Authorization':`Bearer ${session?.access_token}`},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error);return data},[session]);
const fetchProfile=useCallback(async()=>{if(!session)return;setLoading(true);setError('');try{let data=await api();if(!data)data=await api('POST',{full_name:user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Passenger'});setProfile(data);setName(data.full_name)}catch(e){setError(e instanceof Error?e.message:'Unable to load your profile.')}finally{setLoading(false)}},[api,session,user]);
useEffect(()=>{fetchProfile()},[fetchProfile]);
const saveName=async(e:FormEvent)=>{e.preventDefault();if(name.trim().length<2)return setError('Name must contain at least 2 characters.');try{await api('PUT',{full_name:name});setEditing(false);setToast('Profile updated successfully.');await fetchProfile()}catch(e){setError(e instanceof Error?e.message:'Update failed.')}};
const changePassword=async(e:FormEvent)=>{e.preventDefault();if(newPassword.length<8||!/[A-Z]/.test(newPassword)||!/[0-9]/.test(newPassword))return setError('Password needs 8+ characters, an uppercase letter, and a number.');const{error:updateError}=await supabase.auth.updateUser({password:newPassword});if(updateError)return setError(updateError.message);setNewPassword('');setPasswordOpen(false);setToast('Password changed securely.');};
useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)},[toast]);
return <div className="dashboard-page"><header className="dash-header"><Brand/><button className="mobile-menu" onClick={()=>setNavOpen(!navOpen)}><Menu/></button><nav className={navOpen?'open':''}><a href="#overview" onClick={()=>setNavOpen(false)}>Overview</a><a href="#account" onClick={()=>setNavOpen(false)}>My account</a><button onClick={signOut}><LogOut size={17}/> Sign out</button></nav></header>
<main className="dash-main"><section className="welcome" id="overview"><div><span className="dash-eyebrow">COMMUTER PORTAL</span><h1>Welcome, {profile?.full_name?.split(' ')[0]||'Passenger'}.</h1><p>Your secure TransitPass account is ready for the road.</p></div><span className="status-pill"><i/> Account active</span></section>
{toast&&<div className="toast"><CheckCircle2 size={19}/>{toast}</div>}{error&&<div className="notice error dash-error">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}
{loading?<div className="dash-grid"><div className="skeleton large"/><div className="skeleton"/></div>:<><section className="stat-grid"><article><span className="stat-icon teal"><BusFront/></span><div><small>Digital pass</small><strong>Ready to apply</strong></div></article><article><span className="stat-icon blue"><ShieldCheck/></span><div><small>Account security</small><strong>Verified access</strong></div></article><article><span className="stat-icon amber"><Clock3/></span><div><small>Session timeout</small><strong>15 minutes</strong></div></article></section>
<section className="dash-grid" id="account"><article className="panel account-panel"><div className="panel-title"><div><span>ACCOUNT DETAILS</span><h2>Personal information</h2></div><button className="secondary-button" onClick={()=>setEditing(!editing)}><Edit3 size={16}/>{editing?'Cancel':'Edit profile'}</button></div>{editing?<form className="inline-form" onSubmit={saveName}><div className="field-group"><label htmlFor="displayName">Full name</label><div className="input-shell"><UserRound size={18}/><input id="displayName" value={name} onChange={e=>setName(e.target.value)}/></div></div><button className="primary-button">Save changes</button></form>:<div className="detail-list"><div><span><UserRound/></span><p><small>Full name</small><strong>{profile?.full_name}</strong></p></div><div><span><Mail/></span><p><small>Email address</small><strong>{profile?.email}</strong></p></div><div><span><ShieldCheck/></span><p><small>Account type</small><strong>{profile?.role}</strong></p></div><div><span><CalendarDays/></span><p><small>Member since</small><strong>{profile&&new Date(profile.created_at).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong></p></div></div>}</article>
<aside className="panel security-panel"><div className="panel-title"><div><span>SECURITY</span><h2>Password & session</h2></div></div><div className="security-callout"><ShieldCheck/><div><strong>Your account is protected</strong><p>Passwords are hashed and your inactive session ends automatically.</p></div></div>{passwordOpen?<form onSubmit={changePassword}><PasswordField id="dash-password" label="New password" value={newPassword} onChange={setNewPassword} autoComplete="new-password"/><div className="button-row"><button type="button" className="ghost-button" onClick={()=>setPasswordOpen(false)}>Cancel</button><button className="primary-button">Change password</button></div></form>:<button className="wide-action" onClick={()=>setPasswordOpen(true)}><span><KeyRound/></span><div><strong>Change password</strong><small>Update your account credentials</small></div></button>}<div className="location-note"><MapPin size={16}/> Session secured for this device</div></aside></section></>}
</main><footer className="dash-footer"><Brand/><p>Secure access for every journey.</p><Link to="/forgot-password">Account help</Link></footer></div>}
