import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CheckCircle2, KeyRound } from 'lucide-react';
import AuthLayout from '../components/AuthLayout';
import PasswordField from '../components/PasswordField';
import supabase from '../lib/supabase';

export default function ResetPassword(){const nav=useNavigate();const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[ready,setReady]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState(false);
useEffect(()=>{supabase.auth.getSession().then(({data})=>setReady(!!data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'||event==='SIGNED_IN')setReady(true)});return()=>subscription.unsubscribe()},[]);
const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(password.length<8||!/[A-Z]/.test(password)||!/[0-9]/.test(password))return setError('Use 8+ characters with an uppercase letter and a number.');if(password!==confirm)return setError('Passwords do not match.');setBusy(true);const{error:updateError}=await supabase.auth.updateUser({password});setBusy(false);if(updateError)return setError(updateError.message);setDone(true);setTimeout(()=>nav('/dashboard'),1800)};
return <AuthLayout><div className="auth-card"><div className="card-heading"><span className="mini-icon"><KeyRound size={20}/></span><h2>Choose a new password</h2><p>Create a strong password you haven’t used before.</p></div>{!ready&&!done?<div className="notice warning">Open this page using the secure link from your verification email.</div>:done?<div className="success-panel"><span><CheckCircle2 size={26}/></span><h3>Password updated</h3><p>Your password was changed securely. Taking you to your account…</p></div>:<form onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<PasswordField id="new-password" label="New password" value={password} onChange={setPassword} autoComplete="new-password"/><PasswordField id="confirm-password" label="Confirm new password" value={confirm} onChange={setConfirm} autoComplete="new-password"/><button className="primary-button" disabled={busy}>{busy?<span className="button-loader"/>:'Update password'}</button></form>}<p className="auth-switch"><Link to="/login">Return to sign in</Link></p></div></AuthLayout>}
